name: 'maint'

on:
  workflow_dispatch:
    inputs:
      clear_failed_packages:
        description: 'clear_failed_packages=mingw-w64-foo,mingw-w64-bar'
        default: ''
        required: false
        type: string
      clear_failed_build_types:
        description: 'clear_failed_build_types=mingw64,clang64'
        default: ''
        required: false
        type: string
      context:
        description: 'Extra information from invoker'
        default: ''
        required: false
        type: string

permissions:
  contents: write

concurrency: maint-nope

jobs:

  schedule:
    runs-on: ubuntu-22.04

    steps:

    - name: Dump inputs
      if: ${{ github.event_name == 'workflow_dispatch' }}
      env:
        CONTEXT: '${{ toJSON(github.event.inputs) }}'
      run: |
        echo "$CONTEXT"

    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'
        cache-dependency-path: 'requirements.txt'

    - name: Install deps
      env:
        PIP_DISABLE_PIP_VERSION_CHECK: 1
      run: |
        python -m pip install --user -r requirements.txt

    - name: Clear failed build types
      if: ${{ github.event.inputs.clear_failed_build_types != '' }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_TOKEN_READONLY: ${{ secrets.GITHUBTOKENREADONLY }}
        CLEAR_FAILED_BUILD_TYPES: ${{ github.event.inputs.clear_failed_build_types }}
      run: |
        python -u autobuild.py clear-failed --build-types "$CLEAR_FAILED_BUILD_TYPES"
        python -u autobuild.py update-status

    - name: Clear failed packages
      if: ${{ github.event.inputs.clear_failed_packages != '' }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_TOKEN_READONLY: ${{ secrets.GITHUBTOKENREADONLY }}
        CLEAR_FAILED_PACKAGES: ${{ github.event.inputs.clear_failed_packages }}
      run: |
        python -u autobuild.py clear-failed --packages "$CLEAR_FAILED_PACKAGES"
        python -u autobuild.py update-status
